# -*- coding: utf-8 -*-
"""ColorExtractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ib7skMQR89NkMc_jPest3LDysD-fnFuV
"""

from PIL import Image
Image.open('devdas-2.png')

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

image = 'devdas-2.png'
image = Image.open(image).convert('RGB')
image = np.array(image)
w, h, d = image.shape
pixels = np.reshape(image, (w * h, d))
from sklearn.cluster import KMeans
n_colors = 7
model = KMeans(n_clusters=n_colors, random_state=42).fit(pixels)
palette = np.uint8(model.cluster_centers_)
plt.imshow([palette])
plt.show()

